import { MuiThemeProvider } from '@/providers/muiThemeProvider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import { Roboto_Flex } from 'next/font/google';

import Header from '@/components/header/Header';
import './globals.css';

const roboto = Roboto_Flex({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <AppRouterCacheProvider>
          <MuiThemeProvider>
            <Header />
            {children}
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
