import type { Metadata } from 'next';
import { Roboto_Flex } from 'next/font/google';

import './globals.css';
import Header from '@/components/header/Header';

const roboto = Roboto_Flex({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
